services:
  web:
    build: .
    ports:
      - "8080:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/profilesdb
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: profilesdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: